#******************************************************************
#
# Copyright 2018 OHSUNG ELECTRONICS All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('examples_env')

# // [20191008 hyoungjoon.lee] added path(resource/c_common/ocrandom/include) to fix compile error by 1.3.1
examples_env.AppendUnique(CPPPATH=[
    '#/resource/csdk/connectivity/api',
    '#/resource/csdk/security/include/experimental',
    '#/resource/csdk/security/provisioning/include',
    '#/resource/csdk/security/provisioning/include/internal',
    '#/resource/c_common/ocrandom/include'
])

# // [20191008 hyoungjoon.lee] added build option - SECURED
if(examples_env.get('SECURED') == '1'):
	examples_env.AppendUnique(LIBS=['ocprovision'])
# // [20191008 hyoungjoon.lee] added build option - SECURED

examples_env.SConscript('#/../model/SConscript')
examples_env.SConscript('client/SConscript', exports='examples_env')
examples_env.SConscript('server/SConscript', exports='examples_env')