#******************************************************************
#
# Copyright 2018 OHSUNG ELECTRONICS All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('examples_env')

examples_env.AppendUnique(LIBPATH=['/usr/local/lib'])
examples_env.AppendUnique(LIBS=['z', 'hiredis'])
examples_env.AppendUnique(CPPPATH=[
    '#/resource/csdk/connectivity/api',
    '#/resource/csdk/security/include/experimental',
    '#/resource/csdk/security/provisioning/include',
    '#/resource/csdk/security/provisioning/include/internal',
    '#/resource/c_common/ocrandom/include',
    '/usr/local/include/hiredis',
])

if(examples_env.get('SECURED') == '1'):
	examples_env.AppendUnique(LIBS=['ocprovision'])

examples_env.SConscript('#/../model/SConscript')
examples_env.SConscript('BluetoothSpeaker/SConscript', exports='examples_env')
examples_env.SConscript('SmartLED/SConscript', exports='examples_env')
examples_env.SConscript('server/SConscript', exports='examples_env')
