#******************************************************************
#
# Copyright 2018 OHSUNG ELECTRONICS All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('examples_env')

target_arch = examples_env.get('TARGET_ARCH')


examples_env.AppendUnique(CPPPATH=[
	Dir('.').srcnode().path
])

if examples_env.get('SECURED') == '1':
    examples_env.AppendUnique(LIBS=[
        'mbedtls',
        'mbedx509',
        'mbedcrypto'
    ])

ocf_server_sensor_files = [
	'SensorServer.cpp',
	'SensorResource.cpp',
	'SensorDetect.cpp',
]

examples_env.AppendUnique(LIBS=['wiringPi', 'crypt'])

output = examples_env.Program(ocf_server_sensor_files)

# // [20191008 hyoungjoon.lee] removed to fix compile error by 1.3.1
#cbor = examples_env.ScanJSON()
#examples_env.Alias("install", cbor)
#output += cbor
#examples_env.UserInstallTargetExtra(output)
# // [20191008 hyoungjoon.lee] removed to fix compile error by 1.3.1

examples_env.Alias("output", output)
examples_env.AppendTarget('output')
examples_env.Alias("install", output)

