#******************************************************************
#
# Copyright 2018 OHSUNG ELECTRONICS All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('examples_env')


examples_env.AppendUnique(CPPPATH=[
	Dir('.').srcnode().path
])

examples_env.Append(LIBS=['devMgmt','bluetooth'])
examples_env.Append(LIBPATH=['#/../model', '/usr/lib', '/usr/local/lib'])
examples_env.Append(CPPDEFINES=['DEVMGMT_TEST_MODE_ON'])

client_files = [
	'Client.cpp',
	'GenericModel.cpp',
	'Util.cpp',
	'Bluetooth.cpp',
]
output = examples_env.Program(client_files)

examples_env.Alias("output", output)
examples_env.AppendTarget('output')
examples_env.Alias("install", output)

